# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabCli < Formula
  desc "Do a few dumb things with the Gitlab cli, probably not what you want."
  homepage "https://github.com/albertrdixon/gitlab-cli"
  url "https://github.com/albertrdixon/gitlab-cli/releases/download/v0.0.1/gitlab-cli_0.0.1_Darwin_x86_64.tar.gz"
  version "0.0.1"
  sha256 "5dc03a90f83bc706e398ad14d7cf2024dfa6ccd891539d01e37ee01abb1a483d"

  def install
    bin.install "gitlab-cli"
  end

  test do
    system "#{bin}/gitlab-cli --version"
  end
end
